version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis  # J'ai utilisé Redis
    # TODO No you don't !
    # Redis is not used in your code
    # you are not using volumes to persist data

  #TODO the 
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Mappe le port Redis
