version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis  # J'ai utilisé Redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Mappe le port Redis
